# encoding: utf-8
# Autogenerated by the db:seed:dump task
# Do not hesitate to tweak this to your needs

Assignment.create([
  { :due_date => "2013-07-14 23:00:00", :name => "Test Assignment", :created_at => "2013-07-15 10:30:43", :updated_at => "2013-07-15 10:32:01", :description => "Test Description", :event_id => 1, :file => nil }
], :without_protection => true )



Calendar.create([
  { :date => nil, :time_slot => nil, :created_at => nil, :updated_at => nil }
], :without_protection => true )



Company.create([
  { :name => "Test Company", :description => "Test Company", :email => "test@compnay.com", :created_at => "2013-07-15 16:04:25", :updated_at => "2013-07-15 16:04:25" }
], :without_protection => true )



Course.create([
  { :name => nil, :description => nil, :created_at => "2013-07-13 18:11:45", :updated_at => "2013-07-13 18:11:45" },
  { :name => nil, :description => nil, :created_at => "2013-07-13 18:12:35", :updated_at => "2013-07-13 18:12:35" },
  { :name => "Test Course", :description => "Test description", :created_at => "2013-07-15 15:10:34", :updated_at => "2013-07-15 15:10:34" }
], :without_protection => true )



Event.create([
  { :scheduled_date => "2013-07-15", :time_slot => "1", :name => "Test Event", :description => nil, :created_at => "2013-07-13 18:12:35", :updated_at => "2013-07-16 09:09:29", :teacher => 1, :room_id => 1 },
  { :scheduled_date => "2013-07-16", :time_slot => "2", :name => "Test Event 2", :description => "test", :created_at => "2013-07-16 09:39:14", :updated_at => "2013-07-16 09:39:14", :teacher => 2, :room_id => 2 },
  { :scheduled_date => "2013-07-19", :time_slot => "1", :name => "test", :description => "test", :created_at => "2013-07-16 17:38:30", :updated_at => "2013-07-16 17:38:30", :teacher => 2, :room_id => 1 },
  { :scheduled_date => "2013-07-18", :time_slot => "2", :name => "test", :description => "test12", :created_at => "2013-07-16 17:44:49", :updated_at => "2013-07-16 17:44:49", :teacher => 2, :room_id => 2 },
  { :scheduled_date => "2013-08-01", :time_slot => "4", :name => "fill the gap", :description => "wew", :created_at => "2013-07-18 19:05:21", :updated_at => "2013-07-18 19:05:21", :teacher => 2, :room_id => 1 }
], :without_protection => true )



Location.create([
  { :address => "9 Back Hill, London, UK", :company_id => 1, :created_at => "2013-07-15 16:05:17", :updated_at => "2013-07-15 16:06:14" }
], :without_protection => true )



Material.create([
  { :file => nil, :created_at => "2013-07-15 16:09:12", :updated_at => "2013-07-15 16:15:45", :event_id => 1 }
], :without_protection => true )



Person.create([
  { :name => "Ankoor", :surname => "Patel", :email => "ankoor.p@gmail.com", :password_digest => nil, :phone => nil, :created_at => "2013-07-15 09:18:45", :updated_at => "2013-07-15 09:18:45", :role => "admin" },
  { :name => "Admin", :surname => "Admin", :email => "ankoor.p+test@gmail.com", :password_digest => "$2a$10$sSv.uw9t2N.N/Od8nek8yOsEk.w8XIT2OaePDEfh1MtqIv1Tgm5Lm", :phone => "", :created_at => "2013-07-15 15:52:00", :updated_at => "2013-07-15 16:00:50", :role => "admin" },
  { :name => "Test User", :surname => "test", :email => "ankoor.p+testuser@gmail.com", :password_digest => "$2a$10$nM2PyxoimSNLCldrg08aoeRSe6uT7EGT9HByF6VT6Lrf3soV3CIH6", :phone => "099", :created_at => "2013-07-15 16:02:42", :updated_at => "2013-07-15 16:02:42", :role => "user" },
  { :name => "new", :surname => "fdf", :email => "e@gmail.com", :password_digest => "$2a$10$i1QJr8uaiDcsROWpmFdzruvqhUvWrsRImKoHrWa4KJMLlwtXOnRLm", :phone => "ds", :created_at => "2013-07-18 13:37:08", :updated_at => "2013-07-18 13:37:08", :role => "user" },
  { :name => "fdd", :surname => "f", :email => "f@gmail.com", :password_digest => "$2a$10$O.Fc4nXxsScsfb0iGU8D6.57QMHnc2Ho9crPGG3/xWnmEU.QWrTNu", :phone => "f", :created_at => "2013-07-18 13:40:21", :updated_at => "2013-07-18 18:34:43", :role => "teacher" }
], :without_protection => true )



Room.create([
  { :name => "test room", :address => "test room", :size => 20, :created_at => "2013-07-15 16:07:13", :updated_at => "2013-07-15 16:07:13", :location_id => 1 },
  { :name => "test room 2", :address => "next to test room", :size => 30, :created_at => "2013-07-15 16:08:05", :updated_at => "2013-07-15 16:08:05", :location_id => 1 }
], :without_protection => true )



TimeSlot.create([
  { :name => "09:00 - 12:00", :created_at => "2013-07-16 15:44:20", :updated_at => "2013-07-16 15:44:20" },
  { :name => "13:00 - 15:00", :created_at => "2013-07-16 15:44:44", :updated_at => "2013-07-16 15:44:44" },
  { :name => "15:00 - 17:00", :created_at => "2013-07-16 15:44:57", :updated_at => "2013-07-16 15:44:57" },
  { :name => "19:00 - 21:00", :created_at => "2013-07-16 15:45:09", :updated_at => "2013-07-16 15:45:09" }
], :without_protection => true )


