# encoding: utf-8
# Autogenerated by the db:seed:dump task
# Do not hesitate to tweak this to your needs

Assignment.create([
  { :due_date => "2013-07-14 23:00:00", :name => "Test Assignment", :created_at => "2013-07-15 10:30:43", :updated_at => "2013-07-15 10:32:01", :description => "Test Description", :event_id => 1, :file => nil }
], :without_protection => true )



Calendar.create([
  { :date => nil, :time_slot => nil, :created_at => nil, :updated_at => nil }
], :without_protection => true )



Company.create([
  { :name => "Test Company", :description => "Test Company", :email => "test@compnay.com", :created_at => "2013-07-15 16:04:25", :updated_at => "2013-07-15 16:04:25" }
], :without_protection => true )



Course.create([
  { :name => nil, :description => nil, :created_at => "2013-07-13 18:11:45", :updated_at => "2013-07-13 18:11:45" },
  { :name => nil, :description => nil, :created_at => "2013-07-13 18:12:35", :updated_at => "2013-07-13 18:12:35" },
  { :name => "Test Course", :description => "Test description", :created_at => "2013-07-15 15:10:34", :updated_at => "2013-07-15 15:10:34" }
], :without_protection => true )



Event.create([
  { :date => "2013-07-15", :time_slot => "1", :name => "Test Event", :description => nil, :created_at => "2013-07-13 18:12:35", :updated_at => "2013-07-15 09:25:06", :teacher => 1, :room_id => nil }
], :without_protection => true )



Location.create([
  { :address => "9 Back Hill, London, UK", :company_id => 1, :created_at => "2013-07-15 16:05:17", :updated_at => "2013-07-15 16:06:14" }
], :without_protection => true )



Material.create([
  { :file => nil, :created_at => "2013-07-15 16:09:12", :updated_at => "2013-07-15 16:15:45", :event_id => 1 }
], :without_protection => true )



Person.create([
  { :name => "Ankoor", :surname => "Patel", :email => "ankoor.p@gmail.com", :password_digest => nil, :phone => nil, :created_at => "2013-07-15 09:18:45", :updated_at => "2013-07-15 09:18:45", :role => "admin" },
  { :name => "Admin", :surname => "Admin", :email => "ankoor.p+test@gmail.com", :password_digest => "$2a$10$sSv.uw9t2N.N/Od8nek8yOsEk.w8XIT2OaePDEfh1MtqIv1Tgm5Lm", :phone => "", :created_at => "2013-07-15 15:52:00", :updated_at => "2013-07-15 16:00:50", :role => "admin" },
  { :name => "Test User", :surname => "test", :email => "ankoor.p+testuser@gmail.com", :password_digest => "$2a$10$nM2PyxoimSNLCldrg08aoeRSe6uT7EGT9HByF6VT6Lrf3soV3CIH6", :phone => "099", :created_at => "2013-07-15 16:02:42", :updated_at => "2013-07-15 16:02:42", :role => "user" }
], :without_protection => true )



Room.create([
  { :name => "test room", :address => "test room", :size => 20, :created_at => "2013-07-15 16:07:13", :updated_at => "2013-07-15 16:07:13", :location_id => 1 },
  { :name => "test room 2", :address => "next to test room", :size => 30, :created_at => "2013-07-15 16:08:05", :updated_at => "2013-07-15 16:08:05", :location_id => 1 }
], :without_protection => true )


